export const SET_WORKING_OUT = 'SET_WORKING_OUT';
export const GET_WORKING_OUT = 'GET_WORKING_OUT';
export const GET_CURRENT_STATS = 'GET_CURRENT_STATS';
export const GET_CURRENT_WORKOUT = 'GET_CURRENT_WORKOUT';
export const COMPLETE_EXERCISE = 'COMPLETE_EXERCISE';
export const FINISH_WORKOUT = 'FINISH_WORKOUT';
export const GET_NEW_WORKOUT = 'GET_NEW_WORKOUT';
